#accept
deployment:
  user: one2one
  owner: "one2one:one2one"
  from: /var/lib/jenkins/jobs/121Sys/workspace/
  to: www/accept_env
  excludes:
    - upload
    - application/logs
releases:
  enabled: true
  max: 6
  symlink: 121sys_lhs
  directory: releases/121sys_releases/121sys_lhs
hosts:
    - www.leadcontrol.co.uk:2020
tasks:
  pre-deploy:
  on-deploy:
    - uploadFolder
    - datafilesFolder
    - logFolder
    - prepareAcceptLhsDeployment
#    - permissionsGroup
  post-release:
    - databaseBackup: {user: one2one_acc_lhs, pass: I9C2^MgGWZM2, host: localhost, database: one2one_accept_lhs}
  post-deploy: