#production
deployment:
  user: samba
  from: /var/lib/jenkins/jobs/121Sys/workspace/
  to: /var/www/demo_env
  excludes:
    - upload
    - application/logs
releases:
  enabled: true
  max: 6
  symlink: 121sys
  directory: releases/121sys_releases
hosts:
    - 10.10.1.13
tasks:
  pre-deploy:
  on-deploy:
    - uploadFolder
    - logFolder
    - prepareDemoDeployment
    - permissionsGroup
  post-release:
    - databaseBackup: {user: 121sys_demo, pass: UuXWzT2WAwBabjHj, host: localhost, database: 121sys_demo}
  post-deploy: