#production
deployment:
  user: samba
  from: /var/lib/jenkins/jobs/121Sys/workspace/
  to: /var/www
  excludes:
    - upload
    - application/logs
releases:
  enabled: true
  max: 10
  symlink: 121sys_hsl
  directory: releases/121sys_releases/121sys_hsl
hosts:
    - 10.10.1.13
tasks:
  pre-deploy:
  on-deploy:
    - uploadFolder
    - logFolder
    - prepareHslDeployment
    - permissionsGroup
  post-release:
    - databaseBackup: {user: 121sys_hsl, pass: vHF6U2X6ncSK5rNY, host: localhost, database: 121sys_hsl}
  post-deploy: