#production
deployment:
  user: samba
  from: /var/lib/jenkins/jobs/121Sys/workspace/
  to: /var/www
  excludes:
    - upload
    - application/logs
releases:
  enabled: true
  max: 4
  symlink: 121sys_jonwall
  directory: releases/121sys_releases/121sys_jonwall
hosts:
    - 10.10.1.13
tasks:
  pre-deploy:
  on-deploy:
    - uploadFolder
    - logFolder
    - prepareJonWallDeployment
    - permissionsGroup
  post-release:
    - databaseBackup: {user: 121sys_jonwall, pass: QHUtJResGFr8AMDD, host: localhost, database: 121sys_jonwall}
  post-deploy: