#production
deployment:
  user: one2one
  from: /var/lib/jenkins/jobs/121Sys/workspace/
  to: www
  excludes:
    - upload
    - application/logs
releases:
  enabled: true
  max: 6
  symlink: 121sys_lhs
  directory: releases/121sys_releases/121sys_lhs
hosts:
    - www.leadcontrol.co.uk:2020
tasks:
  pre-deploy:
  on-deploy:
    - uploadFolder
    - logFolder
    - prepareLhsDeployment
#    - permissionsGroup
  post-release:
    - databaseBackup: {user: one2one_lhs, pass: Og0ZnpvE2pus, host: localhost, database: one2one_lhs}
  post-deploy:
    - lhsFunctionTriggers