#production
deployment:
  user: samba
  from: /var/lib/jenkins/jobs/121Sys/workspace/
  to: /var/www
  excludes:
    - upload
    - application/logs
releases:
  enabled: true
  max: 6
  symlink: 121sys
  directory: releases/121sys_releases/121sys
hosts:
    - 10.10.1.13
tasks:
  pre-deploy:
  on-deploy:
    - uploadFolder
    - logFolder
    - prepareDeployment
    - permissionsGroup
  post-release:
    - databaseBackup: {user: 121sys, pass: Bu4XNm3Q6fqntySp, host: localhost, database: 121sys}
  post-deploy: