#production
deployment:
  user: samba
  from: /var/lib/jenkins/jobs/121Sys/workspace/
  to: /var/www
  excludes:
    - upload
    - application/logs
releases:
  enabled: true
  max: 4
  symlink: 121sys_prosales
  directory: releases/121sys_releases/121sys_prosales
hosts:
    - 10.10.1.13
tasks:
  pre-deploy:
  on-deploy:
    - uploadFolder
    - logFolder
    - prepareProSalesDeployment
    - permissionsGroup
  post-release:
    - databaseBackup: {user: 121sys_prosales, pass: ca2fUAYMzh28VJ9Z, host: localhost, database: 121sys_prosales}
  post-deploy: