#production
deployment:
  user: one2one
  from: /var/lib/jenkins/jobs/121Sys/workspace/
  to: www
  excludes:
    - upload
    - application/logs
releases:
  enabled: true
  max: 6
  symlink: 121sys_prosales
  directory: releases/121sys_releases/121sys_prosales
hosts:
    - www.leadcontrol.co.uk:2020
tasks:
  pre-deploy:
  on-deploy:
    - uploadFolder
    - logFolder
    - prepareProSalesUkFastDeployment
#    - permissionsGroup
  post-release:
    - databaseBackup: {user: one2one_prosales, pass: ca2fUAYMzh28VJ9Z, host: localhost, database: one2one_prosales}
  post-deploy: