#test
deployment:
  user: estebanc
  from: /var/lib/jenkins/jobs/121SYS/workspace/
  to: /var/www/html
  excludes:
    - upload
releases:
  enabled: true
  max: 3
  symlink: 121sys
  directory: releases/121sys_releases/121sys
hosts:
    - 10.10.1.15
tasks:
  pre-deploy:
  on-deploy:
    - uploadFolder
    - prepareTestDeployment
    - permissionsGroup
  post-release:
    - databaseBackup: {user: 121sys, pass: SRKuMbrmBGm8evZd, host: localhost, database: 121sys}
  post-deploy: