#test
deployment:
  user: estebanc
  from: /var/lib/jenkins/jobs/121Sys/workspace/
  to: /var/www/html
  excludes:
    - upload
    - application/logs
releases:
  enabled: true
  max: 6
  symlink: 121sys
  directory: releases/121sys_releases/121sys
hosts:
    - 10.10.1.15
tasks:
  pre-deploy:
  on-deploy:
    - uploadFolder
    - logFolder
    - prepareTestDeployment
    - permissionsGroup
  post-release:
    - databaseBackup: {user: 121sys_test, pass: SRKuMbrmBGm8evZd, host: localhost, database: 121sys_test}
  post-deploy: